import { Component, OnInit } from '@angular/core';

const dataBase: any = {
  bugs: {
    bz1234: {
      id: 2121,
      importance: 'P5',
      milestone: 8.2,
      desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam malesuada a augue quis eleifend. Maecenas nibh urna, commodo quis velit ut, posuere molestie diam. Mauris urna arcu, convallis eu tellus vel, tempor convallis augue. Integer enim dolor, efficitur in vestibulum sit amet, aliquet at sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate sit amet eros quis finibus. Nam consequat gravida mauris nec tristique. Fusce non nibh nec tortor sagittis cursus vel in turpis. Etiam quis sollicitudin ex. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse pellentesque bibendum libero, et suscipit justo vulputate a. Pellentesque condimentum vel dolor at egestas.     Sed orci est, consequat ac ante quis, auctor porta lectus. Nullam ut tincidunt lacus. Vivamus eget sapien mauris. Curabitur urna massa, sagittis quis accumsan et, semper interdum tellus. Quisque sodales lectus et tellus malesuada consequat. Integer ullamcorper justo ac erat lobortis fringilla. Pellentesque posuere bibendum nisl non lobortis. Sed pharetra tincidunt sapien, sit amet tempor erat vulputate et. Suspendisse et feugiat dui. Aliquam interdum ligula a massa volutpat venenatis. Nam ut sem turpis. Morbi porttitor erat rhoncus felis luctus semper. In hac habitasse platea dictumst. Fusce in metus porta, finibus elit a, mattis ipsum. Pellentesque eu mauris id metus pulvinar maximus. Mauris mattis tempus vulputate. Aliquam odio metus, facilisis non pellentesque nec, posuere et nunc. Praesent posuere mi vitae dolor feugiat maximus. Aliquam nec metus imperdiet est pellentesque lobortis ac ut odio. Vestibulum euismod, leo nec tempor bibendum, orci lacus fringilla ipsum, venenatis tincidunt lorem mauris sed ante. Donec at enim ipsum. Sed condimentum quam sit amet dignissim sodales. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed ullamcorper suscipit cursus. Nullam vitae odio mi. Sed ultricies, lorem in consequat convallis, urna ex cursus velit, a facilisis nunc ante et justo. Sed urna mauris, lacinia id felis tincidunt, consequat bibendum neque. Nulla elementum leo felis, convallis pulvinar dui luctus in. In at volutpat metus. Morbi dignissim velit a nulla sagittis, in laoreet neque cursus. Vestibulum egestas enim at arcu interdum, id vulputate magna lobortis. Vivamus id ligula risus. In sit amet facilisis sem. Nunc id elementum erat, ut bibendum massa. Duis faucibus hendrerit enim, id porta tellus molestie vel. Duis laoreet dapibus pellentesque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur fringilla erat nec justo pharetra, et accumsan tortor lacinia. Praesent dictum, lorem eget placerat fermentum, tellus metus auctor odio, et accumsan purus ex nec tortor. Aenean in metus vel orci maximus cursus id sed lectus."
    },
    bz11234: {
      id: 19085,
      importance: 'P2',
      milestone: 8.3,
      desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam malesuada a augue quis eleifend. Maecenas nibh urna, commodo quis velit ut, posuere molestie diam. Mauris urna arcu, convallis eu tellus vel, tempor convallis augue. Integer enim dolor, efficitur in vestibulum sit amet, aliquet at sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate sit amet eros quis finibus. Nam consequat gravida mauris nec tristique. Fusce non nibh nec tortor sagittis cursus vel in turpis. Etiam quis sollicitudin ex. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse pellentesque bibendum libero, et suscipit justo vulputate a. Pellentesque condimentum vel dolor at egestas.     Sed orci est, consequat ac ante quis, auctor porta lectus. Nullam ut tincidunt lacus. Vivamus eget sapien mauris. Curabitur urna massa, sagittis quis accumsan et, semper interdum tellus. Quisque sodales lectus et tellus malesuada consequat. Integer ullamcorper justo ac erat lobortis fringilla. Pellentesque posuere bibendum nisl non lobortis. Sed pharetra tincidunt sapien, sit amet tempor erat vulputate et. Suspendisse et feugiat dui. Aliquam interdum ligula a massa volutpat venenatis. Nam ut sem turpis. Morbi porttitor erat rhoncus felis luctus semper. In hac habitasse platea dictumst. Fusce in metus porta, finibus elit a, mattis ipsum. Pellentesque eu mauris id metus pulvinar maximus. Mauris mattis tempus vulputate. Aliquam odio metus, facilisis non pellentesque nec, posuere et nunc. Praesent posuere mi vitae dolor feugiat maximus. Aliquam nec metus imperdiet est pellentesque lobortis ac ut odio. Vestibulum euismod, leo nec tempor bibendum, orci lacus fringilla ipsum, venenatis tincidunt lorem mauris sed ante. Donec at enim ipsum. Sed condimentum quam sit amet dignissim sodales. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed ullamcorper suscipit cursus. Nullam vitae odio mi. Sed ultricies, lorem in consequat convallis, urna ex cursus velit, a facilisis nunc ante et justo. Sed urna mauris, lacinia id felis tincidunt, consequat bibendum neque. Nulla elementum leo felis, convallis pulvinar dui luctus in. In at volutpat metus. Morbi dignissim velit a nulla sagittis, in laoreet neque cursus. Vestibulum egestas enim at arcu interdum, id vulputate magna lobortis. Vivamus id ligula risus. In sit amet facilisis sem. Nunc id elementum erat, ut bibendum massa. Duis faucibus hendrerit enim, id porta tellus molestie vel. Duis laoreet dapibus pellentesque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur fringilla erat nec justo pharetra, et accumsan tortor lacinia. Praesent dictum, lorem eget placerat fermentum, tellus metus auctor odio, et accumsan purus ex nec tortor. Aenean in metus vel orci maximus cursus id sed lectus."
    },
    bz12354: {
      id: 35468,
      importance: 'P3',
      milestone: 8.4,
      desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam malesuada a augue quis eleifend. Maecenas nibh urna, commodo quis velit ut, posuere molestie diam. Mauris urna arcu, convallis eu tellus vel, tempor convallis augue. Integer enim dolor, efficitur in vestibulum sit amet, aliquet at sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate sit amet eros quis finibus. Nam consequat gravida mauris nec tristique. Fusce non nibh nec tortor sagittis cursus vel in turpis. Etiam quis sollicitudin ex. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse pellentesque bibendum libero, et suscipit justo vulputate a. Pellentesque condimentum vel dolor at egestas.     Sed orci est, consequat ac ante quis, auctor porta lectus. Nullam ut tincidunt lacus. Vivamus eget sapien mauris. Curabitur urna massa, sagittis quis accumsan et, semper interdum tellus. Quisque sodales lectus et tellus malesuada consequat. Integer ullamcorper justo ac erat lobortis fringilla. Pellentesque posuere bibendum nisl non lobortis. Sed pharetra tincidunt sapien, sit amet tempor erat vulputate et. Suspendisse et feugiat dui. Aliquam interdum ligula a massa volutpat venenatis. Nam ut sem turpis. Morbi porttitor erat rhoncus felis luctus semper. In hac habitasse platea dictumst. Fusce in metus porta, finibus elit a, mattis ipsum. Pellentesque eu mauris id metus pulvinar maximus. Mauris mattis tempus vulputate. Aliquam odio metus, facilisis non pellentesque nec, posuere et nunc. Praesent posuere mi vitae dolor feugiat maximus. Aliquam nec metus imperdiet est pellentesque lobortis ac ut odio. Vestibulum euismod, leo nec tempor bibendum, orci lacus fringilla ipsum, venenatis tincidunt lorem mauris sed ante. Donec at enim ipsum. Sed condimentum quam sit amet dignissim sodales. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed ullamcorper suscipit cursus. Nullam vitae odio mi. Sed ultricies, lorem in consequat convallis, urna ex cursus velit, a facilisis nunc ante et justo. Sed urna mauris, lacinia id felis tincidunt, consequat bibendum neque. Nulla elementum leo felis, convallis pulvinar dui luctus in. In at volutpat metus. Morbi dignissim velit a nulla sagittis, in laoreet neque cursus. Vestibulum egestas enim at arcu interdum, id vulputate magna lobortis. Vivamus id ligula risus. In sit amet facilisis sem. Nunc id elementum erat, ut bibendum massa. Duis faucibus hendrerit enim, id porta tellus molestie vel. Duis laoreet dapibus pellentesque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur fringilla erat nec justo pharetra, et accumsan tortor lacinia. Praesent dictum, lorem eget placerat fermentum, tellus metus auctor odio, et accumsan purus ex nec tortor. Aenean in metus vel orci maximus cursus id sed lectus."
    },
    
    bz14354: {
      id: 35468,
      importance: 'P3',
      milestone: 8.4,
      desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam malesuada a augue quis eleifend. Maecenas nibh urna, commodo quis velit ut, posuere molestie diam. Mauris urna arcu, convallis eu tellus vel, tempor convallis augue. Integer enim dolor, efficitur in vestibulum sit amet, aliquet at sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate sit amet eros quis finibus. Nam consequat gravida mauris nec tristique. Fusce non nibh nec tortor sagittis cursus vel in turpis. Etiam quis sollicitudin ex. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse pellentesque bibendum libero, et suscipit justo vulputate a. Pellentesque condimentum vel dolor at egestas.     Sed orci est, consequat ac ante quis, auctor porta lectus. Nullam ut tincidunt lacus. Vivamus eget sapien mauris. Curabitur urna massa, sagittis quis accumsan et, semper interdum tellus. Quisque sodales lectus et tellus malesuada consequat. Integer ullamcorper justo ac erat lobortis fringilla. Pellentesque posuere bibendum nisl non lobortis. Sed pharetra tincidunt sapien, sit amet tempor erat vulputate et. Suspendisse et feugiat dui. Aliquam interdum ligula a massa volutpat venenatis. Nam ut sem turpis. Morbi porttitor erat rhoncus felis luctus semper. In hac habitasse platea dictumst. Fusce in metus porta, finibus elit a, mattis ipsum. Pellentesque eu mauris id metus pulvinar maximus. Mauris mattis tempus vulputate. Aliquam odio metus, facilisis non pellentesque nec, posuere et nunc. Praesent posuere mi vitae dolor feugiat maximus. Aliquam nec metus imperdiet est pellentesque lobortis ac ut odio. Vestibulum euismod, leo nec tempor bibendum, orci lacus fringilla ipsum, venenatis tincidunt lorem mauris sed ante. Donec at enim ipsum. Sed condimentum quam sit amet dignissim sodales. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed ullamcorper suscipit cursus. Nullam vitae odio mi. Sed ultricies, lorem in consequat convallis, urna ex cursus velit, a facilisis nunc ante et justo. Sed urna mauris, lacinia id felis tincidunt, consequat bibendum neque. Nulla elementum leo felis, convallis pulvinar dui luctus in. In at volutpat metus. Morbi dignissim velit a nulla sagittis, in laoreet neque cursus. Vestibulum egestas enim at arcu interdum, id vulputate magna lobortis. Vivamus id ligula risus. In sit amet facilisis sem. Nunc id elementum erat, ut bibendum massa. Duis faucibus hendrerit enim, id porta tellus molestie vel. Duis laoreet dapibus pellentesque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur fringilla erat nec justo pharetra, et accumsan tortor lacinia. Praesent dictum, lorem eget placerat fermentum, tellus metus auctor odio, et accumsan purus ex nec tortor. Aenean in metus vel orci maximus cursus id sed lectus."
    },
    
    bz12254: {
      id: 35468,
      importance: 'P3',
      milestone: 8.4,
      desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam malesuada a augue quis eleifend. Maecenas nibh urna, commodo quis velit ut, posuere molestie diam. Mauris urna arcu, convallis eu tellus vel, tempor convallis augue. Integer enim dolor, efficitur in vestibulum sit amet, aliquet at sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate sit amet eros quis finibus. Nam consequat gravida mauris nec tristique. Fusce non nibh nec tortor sagittis cursus vel in turpis. Etiam quis sollicitudin ex. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse pellentesque bibendum libero, et suscipit justo vulputate a. Pellentesque condimentum vel dolor at egestas.     Sed orci est, consequat ac ante quis, auctor porta lectus. Nullam ut tincidunt lacus. Vivamus eget sapien mauris. Curabitur urna massa, sagittis quis accumsan et, semper interdum tellus. Quisque sodales lectus et tellus malesuada consequat. Integer ullamcorper justo ac erat lobortis fringilla. Pellentesque posuere bibendum nisl non lobortis. Sed pharetra tincidunt sapien, sit amet tempor erat vulputate et. Suspendisse et feugiat dui. Aliquam interdum ligula a massa volutpat venenatis. Nam ut sem turpis. Morbi porttitor erat rhoncus felis luctus semper. In hac habitasse platea dictumst. Fusce in metus porta, finibus elit a, mattis ipsum. Pellentesque eu mauris id metus pulvinar maximus. Mauris mattis tempus vulputate. Aliquam odio metus, facilisis non pellentesque nec, posuere et nunc. Praesent posuere mi vitae dolor feugiat maximus. Aliquam nec metus imperdiet est pellentesque lobortis ac ut odio. Vestibulum euismod, leo nec tempor bibendum, orci lacus fringilla ipsum, venenatis tincidunt lorem mauris sed ante. Donec at enim ipsum. Sed condimentum quam sit amet dignissim sodales. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed ullamcorper suscipit cursus. Nullam vitae odio mi. Sed ultricies, lorem in consequat convallis, urna ex cursus velit, a facilisis nunc ante et justo. Sed urna mauris, lacinia id felis tincidunt, consequat bibendum neque. Nulla elementum leo felis, convallis pulvinar dui luctus in. In at volutpat metus. Morbi dignissim velit a nulla sagittis, in laoreet neque cursus. Vestibulum egestas enim at arcu interdum, id vulputate magna lobortis. Vivamus id ligula risus. In sit amet facilisis sem. Nunc id elementum erat, ut bibendum massa. Duis faucibus hendrerit enim, id porta tellus molestie vel. Duis laoreet dapibus pellentesque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur fringilla erat nec justo pharetra, et accumsan tortor lacinia. Praesent dictum, lorem eget placerat fermentum, tellus metus auctor odio, et accumsan purus ex nec tortor. Aenean in metus vel orci maximus cursus id sed lectus."
    }
  }
};

@Component({
  selector: 'app-education',
  templateUrl: './education.component.html',
  styleUrls: ['./education.component.css']
})
export class EducationComponent implements OnInit {

  objectKeys = Object.keys;
  something = dataBase['bugs'];
  
  constructor() { }

  datas = ['Bug 1254', 'Bug 1234', 'Bug 6533', 'Bug 3464', 'Bug 3453','Bug 2347', 'Bug 6746'];


  ngOnInit() {
  }

}
